from tkinter import*
from PIL import ImageTk, Image
screen=Tk()
screen.geometry("1000x1000")
screen.title("Class 18 Homework")
a=PhotoImage(file="Ronaldiniho.jpg")
screen.iconphoto(False, a)
img=Image.open("Ronaldiniho.jpg")
img1=img.resize((100, 100))
img2=ImageTk.PhotoImage(img1)
l=Label(screen, image=img2)
l.pack()
f=Frame(screen, bg="green", borderwidth=9)
f.pack()
l1=Label(f, text="Back")
l1.pack()
l2=Label(f, text="Forward")
l2.pack()
l3=Label(f, text="Exit")
l3.pack()
b1=Button(f, text="Click here")
b1.pack()

screen.mainloop()